Feat: Endpoint login-Task 11
Codifica2/task-now-backend pull request #21
Opened 2023-05-07 01:51 UTC by daguilem

2023-05-07 18:51 UTC, PPYanez requested changes

2023-05-07 18:51 UTC, PPYanez commented on controllers/users.js
> +usersRouter.post('/login', async (request,response)=>{
debería ser /api/login, no estaba especificado en la tarjeta así que mb

2023-05-07 18:51 UTC, PPYanez commented on controllers/users.js
> +    console.log(checkPassword)
borrar el console log

2023-05-08 17:03 UTC, PPYanez approved these changes

2023-05-08 18:34 UTC, badsebita approved these changes

2023-05-08 18:46 UTC, merged